package com.ddnr.find11st.model

import com.ddnr.find11st.Products
import org.simpleframework.xml.Element
import org.simpleframework.xml.ElementList
import org.simpleframework.xml.Root

/**
 *
 *
Category(categoryName=브랜드 여성의류, categoryCode=1001295, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001295.png, children=null, subCategory=null)
Category(categoryName=브랜드 남성의류, categoryCode=1001296, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001296.png, children=null, subCategory=null)
Category(categoryName=브랜드 언더웨어, categoryCode=1001297, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001297.png, children=null, subCategory=null)
Category(categoryName=브랜드 여성신발, categoryCode=1001298, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001298.png, children=null, subCategory=null)
Category(categoryName=브랜드 남성신발, categoryCode=1001299, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001299.png, children=null, subCategory=null)
Category(categoryName=브랜드 여성가방, categoryCode=1001300, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001300.png, children=null, subCategory=null)
Category(categoryName=해외직구, categoryCode=8286, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_8286.png, children=null, subCategory=null)
Category(categoryName=브랜드 남성가방, categoryCode=1001301, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001301.png, children=null, subCategory=null)
Category(categoryName=브랜드 여행가방, categoryCode=1001302, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001302.png, children=null, subCategory=null)
Category(categoryName=브랜드 지갑/벨트, categoryCode=1001303, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001303.png, children=null, subCategory=null)
Category(categoryName=브랜드 쥬얼리, categoryCode=1001304, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001304.png, children=null, subCategory=null)
Category(categoryName=브랜드 시계, categoryCode=1001305, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001305.png, children=null, subCategory=null)
Category(categoryName=브랜드 잡화/소품, categoryCode=1001306, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001306.png, children=null, subCategory=null)
Category(categoryName=디자이너 여성의류, categoryCode=1001308, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001308.png, children=null, subCategory=null)
Category(categoryName=수입명품, categoryCode=1001307, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001307.png, children=null, subCategory=null)
Category(categoryName=디자이너 남성의류, categoryCode=1001309, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001309.png, children=null, subCategory=null)
Category(categoryName=디자이너 잡화, categoryCode=1001310, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001310.png, children=null, subCategory=null)
Category(categoryName=여성의류, categoryCode=1001311, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001311.png, children=null, subCategory=null)
Category(categoryName=언더웨어/잠옷, categoryCode=1001313, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001313.png, children=null, subCategory=null)
Category(categoryName=남성의류, categoryCode=1001312, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001312.png, children=null, subCategory=null)
Category(categoryName=남성신발, categoryCode=1001315, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001315.png, children=null, subCategory=null)
Category(categoryName=여성신발, categoryCode=1001314, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001314.png, children=null, subCategory=null)
Category(categoryName=여성가방, categoryCode=1001316, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001316.png, children=null, subCategory=null)
Category(categoryName=남성가방, categoryCode=1001317, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001317.png, children=null, subCategory=null)
Category(categoryName=여행가방/소품, categoryCode=1001318, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001318.png, children=null, subCategory=null)
Category(categoryName=시계, categoryCode=1001319, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001319.png, children=null, subCategory=null)
Category(categoryName=쥬얼리, categoryCode=1001320, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001320.png, children=null, subCategory=null)
Category(categoryName=패션잡화, categoryCode=1001322, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001322.png, children=null, subCategory=null)
Category(categoryName=지갑/벨트, categoryCode=1001321, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001321.png, children=null, subCategory=null)
Category(categoryName=순금/돌반지, categoryCode=1001323, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001323.png, children=null, subCategory=null)
Category(categoryName=스킨케어, categoryCode=1001324, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001324.png, children=null, subCategory=null)
Category(categoryName=메이크업, categoryCode=1001325, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001325.png, children=null, subCategory=null)
Category(categoryName=선케어, categoryCode=1001326, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001326.png, children=null, subCategory=null)
Category(categoryName=남성화장품, categoryCode=1001327, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001327.png, children=null, subCategory=null)
Category(categoryName=향수, categoryCode=1001332, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001332.png, children=null, subCategory=null)
Category(categoryName=클렌징/필링, categoryCode=1001328, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001328.png, children=null, subCategory=null)
Category(categoryName=헤어케어, categoryCode=1001329, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001329.png, children=null, subCategory=null)
Category(categoryName=바디케어, categoryCode=1001330, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001330.png, children=null, subCategory=null)
Category(categoryName=네일케어, categoryCode=1001331, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001331.png, children=null, subCategory=null)
Category(categoryName=뷰티소품, categoryCode=1001333, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001333.png, children=null, subCategory=null)
Category(categoryName=농산, categoryCode=1001334, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001334.png, children=null, subCategory=null)
Category(categoryName=수산, categoryCode=1001335, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001335.png, children=null, subCategory=null)
Category(categoryName=축산, categoryCode=1001336, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001336.png, children=null, subCategory=null)
Category(categoryName=반찬/간편가정식, categoryCode=1001337, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001337.png, children=null, subCategory=null)
Category(categoryName=김치, categoryCode=1058375, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1058375.png, children=null, subCategory=null)
Category(categoryName=가공식품, categoryCode=1001338, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001338.png, children=null, subCategory=null)
Category(categoryName=커피/생수/음료, categoryCode=1001339, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001339.png, children=null, subCategory=null)
Category(categoryName=과자/간식, categoryCode=1001340, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001340.png, children=null, subCategory=null)
Category(categoryName=즉석식품, categoryCode=1001341, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001341.png, children=null, subCategory=null)
Category(categoryName=건강식품, categoryCode=1001342, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001342.png, children=null, subCategory=null)
Category(categoryName=다이어트식품, categoryCode=1001343, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001343.png, children=null, subCategory=null)
Category(categoryName=기저귀, categoryCode=1001344, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001344.png, children=null, subCategory=null)
Category(categoryName=분유, categoryCode=1001345, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001345.png, children=null, subCategory=null)
Category(categoryName=물티슈, categoryCode=1001346, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001346.png, children=null, subCategory=null)
Category(categoryName=출산/돌기념품, categoryCode=1001347, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001347.png, children=null, subCategory=null)
Category(categoryName=이유용품, categoryCode=1001348, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001348.png, children=null, subCategory=null)
Category(categoryName=도서/음반, categoryCode=2967, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_2967.png, children=null, subCategory=null)
Category(categoryName=수유용품, categoryCode=1001349, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001349.png, children=null, subCategory=null)
Category(categoryName=e쿠폰/상품권, categoryCode=117025, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_117025.png, children=null, subCategory=null)
Category(categoryName=유아목욕/스킨케어, categoryCode=1001350, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001350.png, children=null, subCategory=null)
Category(categoryName=여행/숙박/항공, categoryCode=2878, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_2878.png, children=null, subCategory=null)
Category(categoryName=유아세제/위생용품, categoryCode=1001351, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001351.png, children=null, subCategory=null)
Category(categoryName=유아안전/실내용품, categoryCode=1001352, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001352.png, children=null, subCategory=null)
Category(categoryName=외출용품, categoryCode=1001353, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001353.png, children=null, subCategory=null)
Category(categoryName=임부복/소품, categoryCode=1001354, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001354.png, children=null, subCategory=null)
Category(categoryName=티켓/공연, categoryCode=865132, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_865132.png, children=null, subCategory=null)
Category(categoryName=신생아 의류, categoryCode=1001355, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001355.png, children=null, subCategory=null)
Category(categoryName=유아의류, categoryCode=1001356, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001356.png, children=null, subCategory=null)
Category(categoryName=아동/주니어 의류, categoryCode=1001357, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001357.png, children=null, subCategory=null)
Category(categoryName=유아동신발, categoryCode=1001358, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001358.png, children=null, subCategory=null)
Category(categoryName=홈&카서비스, categoryCode=1001122, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001122.png, children=null, subCategory=null)
Category(categoryName=유아동잡화, categoryCode=1001359, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001359.png, children=null, subCategory=null)
Category(categoryName=유아가구/침구, categoryCode=1001360, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001360.png, children=null, subCategory=null)
Category(categoryName=유아동식/영양제, categoryCode=1001361, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001361.png, children=null, subCategory=null)
Category(categoryName=장난감, categoryCode=1001362, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001362.png, children=null, subCategory=null)
Category(categoryName=거실가구, categoryCode=1001363, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001363.png, children=null, subCategory=null)
Category(categoryName=침실가구, categoryCode=1001364, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001364.png, children=null, subCategory=null)
Category(categoryName=아웃도어가구, categoryCode=1001365, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001365.png, children=null, subCategory=null)
Category(categoryName=주방가구, categoryCode=1001366, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001366.png, children=null, subCategory=null)
Category(categoryName=수납가구, categoryCode=1001367, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001367.png, children=null, subCategory=null)
Category(categoryName=유아동가구, categoryCode=1001368, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001368.png, children=null, subCategory=null)
Category(categoryName=서재/사무용가구, categoryCode=1001369, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001369.png, children=null, subCategory=null)
Category(categoryName=DIY자재/용품, categoryCode=1001370, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001370.png, children=null, subCategory=null)
Category(categoryName=리모델링가구, categoryCode=1001371, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001371.png, children=null, subCategory=null)
Category(categoryName=침구, categoryCode=1001372, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001372.png, children=null, subCategory=null)
Category(categoryName=커튼/블라인드, categoryCode=1001373, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001373.png, children=null, subCategory=null)
Category(categoryName=카페트/러그, categoryCode=1001374, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001374.png, children=null, subCategory=null)
Category(categoryName=홈패브릭/수예, categoryCode=1001375, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001375.png, children=null, subCategory=null)
Category(categoryName=조명, categoryCode=1001376, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001376.png, children=null, subCategory=null)
Category(categoryName=인테리어소품, categoryCode=1001377, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001377.png, children=null, subCategory=null)
Category(categoryName=구강/세안/면도, categoryCode=1001378, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001378.png, children=null, subCategory=null)
Category(categoryName=세탁용품, categoryCode=1001379, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001379.png, children=null, subCategory=null)
Category(categoryName=주방용품, categoryCode=1001380, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001380.png, children=null, subCategory=null)
Category(categoryName=욕실용품, categoryCode=1001381, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001381.png, children=null, subCategory=null)
Category(categoryName=청소용품, categoryCode=1001382, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001382.png, children=null, subCategory=null)
Category(categoryName=화장지, categoryCode=1001383, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001383.png, children=null, subCategory=null)
Category(categoryName=생리대/성인기저귀, categoryCode=1001384, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001384.png, children=null, subCategory=null)
Category(categoryName=수납정리용품, categoryCode=1001385, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001385.png, children=null, subCategory=null)
Category(categoryName=세제/방향/살충, categoryCode=1001386, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001386.png, children=null, subCategory=null)
Category(categoryName=생활잡화, categoryCode=1001387, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001387.png, children=null, subCategory=null)
Category(categoryName=주방잡화, categoryCode=1058630, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1058630.png, children=null, subCategory=null)
Category(categoryName=스포츠 의류, categoryCode=1001388, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001388.png, children=null, subCategory=null)
Category(categoryName=스포츠 신발, categoryCode=1001389, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001389.png, children=null, subCategory=null)
Category(categoryName=스포츠 잡화, categoryCode=1001390, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001390.png, children=null, subCategory=null)
Category(categoryName=등산/아웃도어, categoryCode=1001391, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001391.png, children=null, subCategory=null)
Category(categoryName=골프, categoryCode=1001392, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001392.png, children=null, subCategory=null)
Category(categoryName=캠핑, categoryCode=1001393, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001393.png, children=null, subCategory=null)
Category(categoryName=낚시, categoryCode=1001394, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001394.png, children=null, subCategory=null)
Category(categoryName=자전거, categoryCode=1001395, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001395.png, children=null, subCategory=null)
Category(categoryName=헬스, categoryCode=1001396, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001396.png, children=null, subCategory=null)
Category(categoryName=요가/필라테스, categoryCode=1001397, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001397.png, children=null, subCategory=null)
Category(categoryName=스키/보드, categoryCode=1001398, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001398.png, children=null, subCategory=null)
Category(categoryName=전동레저/인라인/킥보드, categoryCode=1001399, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001399.png, children=null, subCategory=null)
Category(categoryName=검도/권투/격투, categoryCode=1001400, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001400.png, children=null, subCategory=null)
Category(categoryName=구기스포츠, categoryCode=1001401, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001401.png, children=null, subCategory=null)
Category(categoryName=라켓스포츠, categoryCode=1001402, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001402.png, children=null, subCategory=null)
Category(categoryName=오토바이/스쿠터, categoryCode=1001403, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001403.png, children=null, subCategory=null)
Category(categoryName=수영, categoryCode=1001404, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001404.png, children=null, subCategory=null)
Category(categoryName=스킨스쿠버/수상레저, categoryCode=1001405, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001405.png, children=null, subCategory=null)
Category(categoryName=기타 스포츠, categoryCode=1001406, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001406.png, children=null, subCategory=null)
Category(categoryName=안마용품, categoryCode=1001407, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001407.png, children=null, subCategory=null)
Category(categoryName=온열/찜질용품, categoryCode=1001408, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001408.png, children=null, subCategory=null)
Category(categoryName=저주파/적외선용품, categoryCode=1001409, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001409.png, children=null, subCategory=null)
Category(categoryName=건강관리용품, categoryCode=1001410, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001410.png, children=null, subCategory=null)
Category(categoryName=건강측정용품, categoryCode=1001411, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001411.png, children=null, subCategory=null)
Category(categoryName=당뇨관리용품, categoryCode=1001412, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001412.png, children=null, subCategory=null)
Category(categoryName=몸매관리용품, categoryCode=1001413, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001413.png, children=null, subCategory=null)
Category(categoryName=눈건강용품, categoryCode=1001414, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001414.png, children=null, subCategory=null)
Category(categoryName=손발건강용품, categoryCode=1001415, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001415.png, children=null, subCategory=null)
Category(categoryName=실버용품, categoryCode=1001416, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001416.png, children=null, subCategory=null)
Category(categoryName=재활운동용품, categoryCode=1001417, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001417.png, children=null, subCategory=null)
Category(categoryName=의약외품, categoryCode=1001418, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001418.png, children=null, subCategory=null)
Category(categoryName=병원/의료용품, categoryCode=1001419, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001419.png, children=null, subCategory=null)
Category(categoryName=자동차용품, categoryCode=1001420, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001420.png, children=null, subCategory=null)
Category(categoryName=자동차기기, categoryCode=1001421, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001421.png, children=null, subCategory=null)
Category(categoryName=공구, categoryCode=1001422, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001422.png, children=null, subCategory=null)
Category(categoryName=전기/산업자재, categoryCode=1001423, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001423.png, children=null, subCategory=null)
Category(categoryName=안전/보안용품, categoryCode=1001424, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001424.png, children=null, subCategory=null)
Category(categoryName=스마트기기, categoryCode=1001425, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001425.png, children=null, subCategory=null)
Category(categoryName=카메라/주변기기, categoryCode=1001426, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001426.png, children=null, subCategory=null)
Category(categoryName=게임, categoryCode=1001427, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001427.png, children=null, subCategory=null)
Category(categoryName=태블릿, categoryCode=1001428, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001428.png, children=null, subCategory=null)
Category(categoryName=휴대폰, categoryCode=1001429, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001429.png, children=null, subCategory=null)
Category(categoryName=TV, categoryCode=1001430, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001430.png, children=null, subCategory=null)
Category(categoryName=냉장고, categoryCode=1001431, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001431.png, children=null, subCategory=null)
Category(categoryName=세탁기, categoryCode=1001432, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001432.png, children=null, subCategory=null)
Category(categoryName=생활가전, categoryCode=1001433, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001433.png, children=null, subCategory=null)
Category(categoryName=주방가전, categoryCode=1001434, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001434.png, children=null, subCategory=null)
Category(categoryName=영상가전, categoryCode=1001435, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001435.png, children=null, subCategory=null)
Category(categoryName=음향가전, categoryCode=1001436, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001436.png, children=null, subCategory=null)
Category(categoryName=이미용가전, categoryCode=1001437, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001437.png, children=null, subCategory=null)
Category(categoryName=계절가전, categoryCode=1001438, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001438.png, children=null, subCategory=null)
Category(categoryName=노트북, categoryCode=1001439, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001439.png, children=null, subCategory=null)
Category(categoryName=데스크탑, categoryCode=1001440, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001440.png, children=null, subCategory=null)
Category(categoryName=모니터, categoryCode=1001441, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001441.png, children=null, subCategory=null)
Category(categoryName=프린터/복합기, categoryCode=1001442, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001442.png, children=null, subCategory=null)
Category(categoryName=저장장치, categoryCode=1001443, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001443.png, children=null, subCategory=null)
Category(categoryName=PC부품, categoryCode=1001444, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001444.png, children=null, subCategory=null)
Category(categoryName=컴퓨터 주변기기, categoryCode=1001445, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001445.png, children=null, subCategory=null)
Category(categoryName=문구/사무용품, categoryCode=1001446, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001446.png, children=null, subCategory=null)
Category(categoryName=화방용품, categoryCode=1001447, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001447.png, children=null, subCategory=null)
Category(categoryName=가전렌탈, categoryCode=1001448, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001448.png, children=null, subCategory=null)
Category(categoryName=꽃배달, categoryCode=1001449, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001449.png, children=null, subCategory=null)
Category(categoryName=꽃/원예, categoryCode=1001450, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001450.png, children=null, subCategory=null)
Category(categoryName=악기, categoryCode=1001451, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001451.png, children=null, subCategory=null)
Category(categoryName=취미, categoryCode=1001452, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001452.png, children=null, subCategory=null)
Category(categoryName=애견용품, categoryCode=1001453, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001453.png, children=null, subCategory=null)
Category(categoryName=고양이용품, categoryCode=1001454, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001454.png, children=null, subCategory=null)
Category(categoryName=조류용품, categoryCode=1001455, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001455.png, children=null, subCategory=null)
Category(categoryName=관상어/수족관, categoryCode=1001456, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001456.png, children=null, subCategory=null)
Category(categoryName=기타 동물용품, categoryCode=1001457, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1001457.png, children=null, subCategory=null)
Category(categoryName=비즈11번가, categoryCode=1059820, totalCount=null, categoryImage=http://m.11st.co.kr/MW/images/categoryImage/android/cate_1059820.png, children=null, subCategory=null)
 * */
@Root(name = "CategoryResponse", strict = false)
data class CategoryResponse(
        @set: Element(name = "Request", required = true)
        @get: Element(name = "Request", required = true)
        var request: Request? = null,

        @set:ElementList(inline = true, name = "RootCategory", required = false)
        @get:ElementList(inline = true, name = "RootCategory", required = false)
        var rootCategory: Category? = null,

        @set:ElementList(inline = true, name = "Category", required = false)
        @get:ElementList(inline = true, name = "Category", required = false)
        var category: List<Category>? = null,

        @set:Element(name = "Products", required = false)
        @get:Element(name = "Products", required = false)
        var products: Products? = null,

        @set:ElementList(name = "Children", required = false)
        @get:ElementList(name = "Children", required = false)
        var children: List<Category>? = null,

        @set:ElementList(name = "SubCategory", required = false)
        @get:ElementList(name = "SubCategory", required = false)
        var subCategory: List<Category>? = null
)
/*
@Root(name = "RootCategory", strict = false)
data class RootCategory(
        @set:Element(name = "CategoryName", required = false, data = true)
        @get:Element(name = "CategoryName", required = false, data = true)
        var categoryName: String? = null,

        @set:Element(name = "CategoryCode", required = false)
        @get:Element(name = "CategoryCode", required = false)
        var categoryCode: String? = null
)*/

@Root(name = "Category", strict = false)
data class Category(
        @set:Element(name = "CategoryName", required = false, data = true)
        @get:Element(name = "CategoryName", required = false, data = true)
        var categoryName: String? = null,

        @set:Element(name = "CategoryCode", required = false)
        @get:Element(name = "CategoryCode", required = false)
        var categoryCode: String? = null,

        @set:Element(name = "TotalCount", required = false)
        @get:Element(name = "TotalCount", required = false)
        var totalCount: String? = null,

        @set:Element(name = "CategoryImage", required = false, data = true)
        @get:Element(name = "CategoryImage", required = false, data = true)
        var categoryImage: String? = null,

        @set:Element(name = "Children", required = false)
        @get:Element(name = "Children", required = false)
        private var children: List<Category>? = null,

        @set:Element(name = "SubCategory", required = false)
        @get:Element(name = "SubCategory", required = false)
        private var subCategory: List<Category>? = null
)